site_name: NOMAD Docs
theme:
  name: material
  palette:
    primary: purple
nav:
  - Home: index.md
  - Setup: setup.md
  - Tutorials:
      - 1. Reading Data: reading-data.md
      - 2. Filtering: filtering.md
      - 3. Stop Detection: stop-detection.md
